news/urls.py
from django.contrib.auth import views as autho_views
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page

app_name = 'news'

urlpatterns = [
    # path('', views.index, name='home'), # http://127.0.0.1:8000/first/index/
    # path('', cache_page(60)(views.HomeNews.as_view()), name='home'),    # в as_vew() мы можем передавать параметры
# устанавливаем кэш главной страницы на одну минуту
    path('', views.HomeNews.as_view(), name='home'), # сравни время загрузки с кэшированием и без

    # path('category/<int:pk>/', views.get_category, name='category'),
    path('category/<int:pk>/', views.NewsByCategory.as_view(), name='category'),

    # path('news/<int:news_id>', views.view_news, name='view_news'),
    path('news/<int:pk>', views.ViewNews.as_view(), name='view_news'),

    # path('news/add-news/', views.add_news, name='add_news'),
    path('news/add-news/', views.CreateNews.as_view(), name='add_news'),

    path('console/', views.console, name='console'),

    path('test-pagination/', views.test_pagination, name='pagination'),

    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),

    path('contact/', views.sender_email, name='contact'),


]


# urlpatterns = [
#     path('index/', views.index1, name='home'), # http://127.0.0.1:8000/first/index/
#     path('console/', views.console, name='console'),
#     path('index/category/<int:pk>/', views.index1, name='category'),
#
#
# ]

templates/inc/_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark"> <!---light bg-light-->
  <a class="navbar-brand" href="{% url 'news:home' %}">News</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item"><a class="nav-link" href="#">Главная</a></li>
      {% if user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" href="{% url 'news:add_news' %}">Добавить новость</a></li>
      <li class="nav-item"><a class="nav-link" href="{% url 'news:contact' %}">Обратная связь</a></li>
      {% endif %}
    </ul>

    <span class="navbar-text">
    {% if user.is_authenticated %}
  Добро пожаловать {{ user.username }} | <a href="{% url 'news:logout' %}">Выход</a>

    {% else %}


        <a href="{% url 'news:register' %}">Регистрация</a> | <a href="{% url 'news:login' %}">Авторизация</a>

    {% endif %}
    </span>

    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

templates/inc/_sidebar.html
{% load news_tags %}

{% comment %}
<div class="list-group">
{% get_list_categories as categories %}
        {% for category in categories %}

<a href="{% url 'news:category' category.pk %}" class="list-group-item list-group-item-action">
    {{category.title}}
</a>
<!--<a href="/first/index/category/{{category.pk}}/" class="list-group-item list-group-item-action"></a>-->

        {% endfor %}


</div>
{% endcomment %}



<!--тег определенный нами в news/templatetags/new_tags.py-->
{% show_categories arg2='User' arg1='Hi' %}